# .github/workflows/ci-cd.yml
name: CI-CD

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
# ──────────────────────────────  TEST  ────────────────────────────── #
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Create .env.test
        run: |
          echo "JWT_SECRET=testSecret" > .env.test
          echo "PORT=4000"            >> .env.test

      - run: npm ci

      - run: npm run lint

      - name: Unit tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Check vulnerabilities
        run: npm audit --production --audit-level=moderate
